### ISSUE TITLE
No module named 'models.networks.sync_batchnorm'

### ISSUE THREAD

**Issue by 1057520143** [microsoft/CoCosNet#13]
When I ran DeepFashion (Posed to image) with the pretraining model, the following error occurred:
`Traceback (most recent call last):
  File "test.py", line 13, in <module>
    from models.pix2pix_model import Pix2PixModel
  File "E:\pythonWork\CoCosNet-master\models\pix2pix_model.py", line 6, in <module>
    import models.networks as networks
  File "E:\pythonWork\CoCosNet-master\models\networks\__init__.py", line 8, in <module>
    from models.networks.loss import *
  File "E:\pythonWork\CoCosNet-master\models\networks\loss.py", line 7, in <module>
    from models.networks.architecture import VGG19
  File "E:\pythonWork\CoCosNet-master\models\networks\architecture.py", line 9, in <module>
    from models.networks.normalization import SPADE, equal_lr, SPADE_TwoPath
  File "E:\pythonWork\CoCosNet-master\models\networks\normalization.py", line 10, in <module>
    from models.networks.sync_batchnorm import SynchronizedBatchNorm2d
ModuleNotFoundError: No module named 'models.networks.sync_batchnorm'`
How to resolve this missing reference file?

**Comment by panzhang0212** [comment]
Do you clone sync_bn?
![image](https://user-images.githubusercontent.com/30363822/90249728-8efd7c00-de6d-11ea-9a23-fbb716ca4624.png)
