### ISSUE TITLE
KeyError: '22233.jpg' on celebahqedge test script

### ISSUE THREAD

**Issue by genekogan** [microsoft/CoCosNet#2]
Running example test command from the readme on `celebahqedge`:

```
python test.py --name celebahqedge --dataset_mode celebahqedge --dataroot ./imgs/celebahqedge/ --gpu_ids 0 --nThreads 0 --batchSize 4 --use_attention --maskmix --PONO --PONO_C --warp_bilinear --adaptor_kernel 4
```

I get this error:

```
Traceback (most recent call last):
  File "test.py", line 19, in <module>
    dataloader.dataset[0]
  File "/home/bzion/projects/CoCosNet/data/pix2pix_dataset.py", line 90, in __getitem__
    val = self.ref_dict[key]
KeyError: '22233.jpg'
```

Digging around, I notice the function `get_ref` in `pix2pix_dataset.py` is implicated, and appears to be not implemented yet? Maybe this is the source of the issue.

```
    def get_ref(self, opt):
        pass
```

This repo looks very exciting.

**Comment by panzhang0212** [comment]
Sorry, I miss some files in the repo. You can clone the repo and try again.

**Comment by genekogan** [comment]
Thank you, it is fixed.
